### ISSUE TITLE
Dataset preprocessing

### ISSUE THREAD

**Issue by Minhah-Saleem** [IBM/Grapher#12]
Hi @imelnyk. 
In the paper, three datasets have been mentioned. 
- WebNLG 
- NYT 
- TekGen
but codes for only webnlg are provided. Can you kindly guide me about the others? where can I get access to those from and how can they be used? 

Also will you be open to sharing the trained model if i just wish to run inference without training, maybe via email. I'm currently working on review of models for my research and just want to check the performance of the system/

**Comment by imelnyk** [comment]
Hi,

- NYT dataset can be found here: https://github.com/xiangrongzeng/copy_re
- TekGen: https://github.com/google-research-datasets/KELM-corpus#part-1-tekgen-training-corpus

The current code is prepared for WebNLG, but it is not very difficult to adapt it to other datasets. It is mostly the DataModule that needs to be changed, the rest remains pretty much the same (you can even use the same evaluation scripts from WebNLG for simplicity).
