### ISSUE TITLE
Encoding in dataset.py:61 json.load()

### ISSUE THREAD

**Issue by dennismenze** [IBM/Grapher#4]
When starting training, I got the following error:

`UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 238339: character maps to <undefined>`

By adding an encoding parameter, the error was resolved:

`D = json.load(open(os.path.join(self.output_path, f'{split}.json'), encoding="utf-8"))`

**Comment by imelnyk** [comment]
Although I did not have this encoding issue on my end, it is great that this simple fix worked for you. Thanks for posting it!
